### ISSUE TITLE
Had to run initial connection on HTTPS

### ISSUE THREAD

**Issue by msurguy** [urish/arduino-slack-bot#1]
For some reason I wasn't able to run this command over HTTP : 

```
  http.begin("https://slack.com/api/rtm.start?token=" + SLACK_BOT_TOKEN);
```

Slack was refusing connection over HTTP and wanted me to use HTTPS. 

I had to use HTTPS connection instead (which I got by examining certificate in a web browser):

```
#define SLACK_SSL_FINGERPRINT "AB F0 5B A9 1A E0 AE 5F CE 32 2E 7C 66 67 49 EC DD 6D 6A 38" // If Slack changes their SSL fingerprint, you would need to update this

  http.begin("https://slack.com/api/rtm.start?token=" + SLACK_BOT_TOKEN, SLACK_SSL_FINGERPRINT);
```

Want me to create a PR for this change?

**Comment by urish** [comment]
Yes, go ahead.

by the way, the original code does create an HTTPS request - strange that it didn't work without the certificate...

**Comment by msurguy** [comment]
@urish My guess it's because newer Arduino version for ESP checks if domain is HTTPS and requires cert in that case:

https://github.com/esp8266/Arduino/commit/81d3bb3e3a052027f8349db1c0f0380306897619

**Comment by urish** [comment]
Seem to make a lot of sense. Looking forward to your PR!
